# Generated by Django 4.0.7 on 2022-08-31 13:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titolo', models.CharField(max_length=250)),
                ('descrizione', wagtail.fields.RichTextField()),
                ('data', models.DateField(verbose_name='data di publicazione')),
                ('documento', models.FileField(upload_to='uploads/% y/% m/% d/')),
                ('copertina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
