# Generated by Django 4.0.7 on 2022-08-31 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_articolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='titolo',
        ),
        migrations.AddField(
            model_name='articolo',
            name='autore',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articolo',
            name='testo',
            field=wagtail.fields.RichTextField(default='testo default'),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='documento',
            field=models.FileField(blank=True, upload_to='uploads/% y/% m/% d/'),
        ),
    ]
