# Generated by Django 4.0.7 on 2022-08-31 14:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_articolo_titolo_articolo_autore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='descrizione',
            field=wagtail.fields.RichTextField(default="descrizione dell'articolo"),
        ),
    ]
