# Generated by Django 4.0.7 on 2022-08-31 15:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_articolo_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='descrizione',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='testo',
            field=wagtail.fields.RichTextField(default=''),
        ),
    ]
