# Generated by Django 4.0.7 on 2022-09-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articolo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articolo',
        ),
    ]
